config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  get 'search-mock' => 'search#index', :as => 'home'
  get 'search-mock/form' => 'search#form', :as => 'form'
  get 'search-mock/results/:document_type' => 'search#results', :as => 'results'
  get 'search-mock/objects' => 'search#object', :as => 'object'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
# # The one and only search controller.
class SearchController < ApplicationController
  
  
  # ## A method to render the home page.
  def index
  end
  
  
  # ## A method to render the search form.
  def form
    json = {
      "title": "this is some pretend configuration json that might surface available facets and etc.",
      "description": "this is a description"
    }
    render( :json => json, status: :ok)
  end
  
  # ## A method to render a results list view.
  def results
    
    # We get the document type from the URL parameter.
    document_type = params[:document_type]
    
    # We substitute the hyphen as supplied in the URL, for an underscrore as used in the template name.
    document_type.gsub!( '-', '_' )
    
    # We render the appropriate template based on the document type and the format requested.
    render :template => "search/results/#{document_type}/results"
  end
  
  # ## A method to render an object view.
  def object
    
    # We get the object uri from the URL object parameter.
    object_uri = params[:object]
    
    # We construct the path to the template file.
    file_path = construct_object_file_path( object_uri )
    
    # We render the appropriate object template.
    render :template => "search/objects/#{file_path}/object"
  end
  
  # ## A method to construct an object file path.
  def construct_object_file_path( object_uri )
    
    # We parse the object URI as a Ruby URI.
    object_uri = URI.parse( object_uri )
    
    # We extract the path from the URI.
    file_path = object_uri.path
    
    # We swap out any slashes for hyphens.
    file_path.gsub!( '/', '-' )
    
    # We strip out the first hyphen.
    file_path = file_path[1..-1]
    
    # We return the file path.
    file_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<%= content_tag( 'h1', 'Mocked up data to prototype search with' ) %>
<ul>
	<%= content_tag( 'li', link_to( 'Form', form_url ) ) %>
	<li>
		<%= content_tag( 'p', 'Results' ) %>
		<ul>
			<%= content_tag( 'li', "Research briefings (#{link_to( 'XML', results_url( :document_type => 'research-briefings', :format => 'xml' ) )} / #{link_to( 'JSON', results_url( :document_type => 'research-briefings', :format => 'json' ) )} / #{link_to( 'Ruby object', results_url( :document_type => 'research-briefings', :format => 'rb' ) )})".html_safe ) %>
			<%= content_tag( 'li', "Written questions (#{link_to( 'XML', results_url( :document_type => 'written-questions', :format => 'xml' ) )} / #{link_to( 'JSON', results_url( :document_type => 'written-questions', :format => 'json' ) )} / #{link_to( 'Ruby object', results_url( :document_type => 'written-questions', :format => 'rb' ) )})".html_safe ) %>
			<%= content_tag( 'li', "Written statements (#{link_to( 'XML', results_url( :document_type => 'written-statements', :format => 'xml' ) )} / #{link_to( 'JSON', results_url( :document_type => 'written-statements', :format => 'json' ) )} / #{link_to( 'Ruby object', results_url( :document_type => 'written-statements', :format => 'rb' ) )})".html_safe ) %>
		</ul>
	</li>
	<li>
		<%= content_tag( 'p', 'Objects' ) %>
		<ul>
			<%= content_tag( 'li', "An EDM (#{link_to( 'XML', object_url( :object => 'http://data.parliament.uk/edms/22468', :format => 'xml' ) )} / #{link_to( 'JSON', object_url( :object => 'http://data.parliament.uk/edms/22468', :format => 'json' ) )} / #{link_to( 'Ruby object', object_url( :object => 'http://data.parliament.uk/edms/22468', :format => 'rb' ) )})".html_safe ) %>
			<%= content_tag( 'li', "A research briefing (#{link_to( 'XML', object_url( :object => 'http://data.parliament.uk/resources/342599', :format => 'xml' ) )} / #{link_to( 'JSON', object_url( :object => 'http://data.parliament.uk/resources/342599', :format => 'json' ) )} / #{link_to( 'Ruby object', object_url( :object => 'http://data.parliament.uk/resources/342599', :format => 'rb' ) )})".html_safe ) %>
			<%= content_tag( 'li', "A written question (#{link_to( 'XML', object_url( :object => 'http://hansard.intranet.data.parliament.uk/Lords/2012-12-10/1212106000156', :format => 'xml' ) )} / #{link_to( 'JSON', object_url( :object => 'http://hansard.intranet.data.parliament.uk/Lords/2012-12-10/1212106000156', :format => 'json' ) )} / #{link_to( 'Ruby object', object_url( :object => 'http://hansard.intranet.data.parliament.uk/Lords/2012-12-10/1212106000156', :format => 'rb' ) )})".html_safe ) %>
			<%= content_tag( 'li', "A written statement (#{link_to( 'XML', object_url( :object => 'http://hansard.intranet.data.parliament.uk/Commons/2012-12-18/12121863000016', :format => 'xml' ) )} / #{link_to( 'JSON', object_url( :object => 'http://hansard.intranet.data.parliament.uk/Commons/2012-12-18/12121863000016', :format => 'json' ) )} / #{link_to( 'Ruby object', object_url( :object => 'http://hansard.intranet.data.parliament.uk/Commons/2012-12-18/12121863000016', :format => 'rb' ) )})".html_safe ) %>
		</ul>
	</li>
</ul>